### PR TITLE
Logo Animation on Landing

### PR DESCRIPTION
**Pull request by njsfield**
image

### CODE REVIEW

**Comment by emilyb7** [comment]
hey nick! jen and i love the animation but both think that black isn't the friendliest colour. Reckon we can go back to the placeholder image?

**Comment by emilyb7** [comment]
noga might come up with some ideas : )

**Comment by njsfield** [comment]
No prob! I've updated to the origin placeholder;
image
Checkout the branch to see it alongside the animation.

**Comment by emilyb7** [comment]
great!

**Comment by njsfield** [comment]
Cool, will reassign when the last css changes/equation animation is previewable

**Comment by emilyb7** [comment]
cool nice work : ) to be honest, I think both animations could still be a bit faster. But not a blocker and I'm happy to hear other opinions. Going to merge now! 🎉 🎉 🎉

**Pull request merged**
